function AtariScreen(a,b,c,d){void 0===d&&(d=!0);this.canvas=b.appendChild(document.createElement("canvas"));this.canvas.id=c;this.canvas.width=640;this.canvas.height=400;this.scale=d;this.screen_memory=new Uint16Array(16E3);this.ready=!0;this.cycles=[];this.mode=this.SetMode(a)}
AtariScreen.prototype.SetMode=function(a){a="undefined"===typeof a?0:a;a=0>a||2<a?0:a;switch(a){case 0:this.planes=4;this.scaleY=this.scaleX=2;this.width=320;this.height=200;this.SetPalette(new Uint16Array([4095,3840,240,4080,15,3855,255,1365,819,3891,1011,4083,831,3903,1023,0]));break;case 1:this.planes=2;this.scaleX=1;this.scaleY=2;this.width=640;this.height=200;this.SetPalette(new Uint16Array([4095,3840,240,0]));break;case 2:this.scaleY=this.scaleX=this.planes=1,this.width=640,this.height=400,
this.SetPalette(new Uint16Array([0,4095]))}return this.mode=a};
AtariScreen.prototype.Display=function(){if(this.ready){this.ready=!1;var a=this.canvas.getContext("2d");this.scale?(this.canvas.width=640,this.canvas.height=400,a.setTransform(1,0,0,1,0,0),a.scale(this.scaleX,this.scaleY),a.imageSmoothingEnabled=!1):(this.canvas.width=this.width,this.canvas.height=this.height);var b=a.createImageData(this.width,this.height),c=this.planes,d=this.screen_memory.length/c,e=0,l=0,f,g,h,k,m=Array(c);for(f=0;f<d;f++){for(g=0;g<c;g++)m[g]=this.screen_memory[l++];for(g=15;-1<
g;--g){for(h=k=0;h<c;h++)m[h]&1<<g&&(k+=1<<h);b.data[e++]=this.pixel_palette[k][0];b.data[e++]=this.pixel_palette[k][1];b.data[e++]=this.pixel_palette[k][2];b.data[e++]=255}}a.putImageData(b,0,0);this.scale&&a.drawImage(this.canvas,0,0);this.ready=!0}return this.ready};AtariScreen.prototype.SetPalette=function(a){this.palette=a;this.canvas_palette=Array(a.length);this.pixel_palette=Array(a.length);this.restore_palette=Array(a.length);for(var b=0;b<a.length;b++)this.SetPaletteValue(b,a[b])};
AtariScreen.prototype.SetPaletteValue=function(a,b){var c=(((b&1792)>>7)+((b&2048)>>11)).toString(16),d=(((b&112)>>3)+((b&128)>>7)).toString(16),e=(((b&7)<<1)+((b&8)>>3)).toString(16);this.canvas_palette[a]="#"+c+c+d+d+e+e;this.pixel_palette[a]=[parseInt(c+c,16),parseInt(d+d,16),parseInt(e+e,16)]};
AtariScreen.prototype.ExtractDegasElite=function(a){var b=new DataView(a),c=b.getUint16(0);this.SetMode(c&255);this.ExtractPalette(b,2);c=0<(c&32768)?this.ExtractRLEData(b,34):this.ExtractPlanarScreen(b,34);if(32==a.byteLength-c)for(this.cycles=[],a=0;4>a;a++){var d={};d.left_colour=b.getUint16(c+2*a);d.right_colour=b.getUint16(c+2*a+8);d.direction=b.getUint16(c+2*a+16)-1;d.delay=Math.round(1E3*(128-b.getUint16(c+2*a+24))/60);this.cycles.push(d)}};
AtariScreen.prototype.ExtractPalette=function(a,b){for(var c=this.palette.length,d=new Uint16Array(c),e=0;e<c;e++)d[e]=a.getUint16(b),b+=2;this.SetPalette(d)};AtariScreen.prototype.ExtractPlanarScreen=function(a,b){for(var c=this.screen_memory.length,d=0;d<c;d++)this.screen_memory[d]=a.getUint16(b),b+=2;return b};
AtariScreen.prototype.ExtractRLEData=function(a,b){var c=this.height,d=this.planes,e=160/d,l=e/2,f,g,h,k,m,n,r;f=new ArrayBuffer(160);var p=new DataView(f),q=0;for(f=0;f<c;f++){for(g=k=0;g<d;g++)for(m=0;m<e;)if(n=a.getUint8(b++),0<(n&128))for(r=256-n+1,n=a.getUint8(b++),h=0;h<r;h++)p.setUint8(k++,n),m++;else for(n++,h=0;h<n;h++)p.setUint8(k++,a.getUint8(b++)),m++;for(g=k=0;g<l;g++){for(h=0;h<d;h++)this.screen_memory[q+h]=p.getUint16(k+h*e);k+=2;q+=d}}return b};
AtariScreen.prototype.StartCycle=function(a,b){void 0===b&&(b=!1);var c=!1;if(0<=a&&3>=a){var d=this.cycles[a];if(0!=d.direction){for(var c=this.pixel_palette,e=c.length,l=this.restore_palette=Array(e),f=0;f<e;f++)l[f]=[c[f][0],c[f][1],c[f][2]];d.position=0;d.length=d.right_colour-d.left_colour+1;d.on=!0;b&&this.StartCycleAnimation(a);c=!0}}return c};
AtariScreen.prototype.GetNextCycle=function(a){var b=!1;if(0<=a&&3>=a){var c=this.cycles[a];if(c.on){b=this.restore_palette;a=this.pixel_palette;var d=c.left_colour,e=d,l=c.right_colour,f=c.position,f=f-c.direction;f>l&&(f=e);f<e&&(f=l);c.position=f;for(var c=c.length,g=0;g<c;g++)f>l&&(f=d),a[e++]=[b[f][0],b[f][1],b[f++][2]];b=!0}}return b};
AtariScreen.prototype.StartCycleAnimation=function(a){var b=-1;0<=a&&3>=a&&(a=this.cycles[a],0!=a.direction&&(b=a.animationId=setInterval(function(a){a.GetNextCycle(0);requestAnimationFrame(function(){a.Display()})},a.delay,this),a.animating=!0));return b};
AtariScreen.prototype.StopCycle=function(a){var b=!1;if(0<=a&&3>=a&&(a=this.cycles[a],a.on)){a.animating&&clearInterval(a.animationId);a.animating=!1;for(var b=this.restore_palette,c=b.length,d=this.pixel_palette=Array(c),e=0;e<c;e++)d[e]=[b[e][0],b[e][1],b[e][2]];a.on=!1;b=!0}return b};